<a href="https://colab.research.google.com/github/4522Dev/eda/blob/main/Module2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Module 2

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dataset= pd.read_csv('https://raw.githubusercontent.com/salemprakash/EDA/main/Data/student-mat.csv')
dataset

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [ ]:
dataset.head(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,12,12,11
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,6,6,5,6
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,16,18,19
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,14,15,15

In [ ]:
df1 = dataset.iloc[:len(dataset)//2]
df2 = dataset.iloc[len(dataset)//2:]
df3 = pd.concat([df1,df2],ignore_index=True)
df3

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [ ]:
pd.concat([df1,df2],axis=1)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18.0,U,GT3,A,4.0,4.0,at_home,teacher,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GP,F,17.0,U,GT3,T,1.0,1.0,at_home,other,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GP,F,15.0,U,LE3,T,1.0,1.0,at_home,other,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GP,F,15.0,U,GT3,T,4.0,2.0,health,services,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GP,F,16.0,U,GT3,T,3.0,3.0,other,other,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,5.0,4.0,4.0,5.0,4.0,11.0,9.0,9.0,9.0
391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,4.0,5.0,3.0,4.0,2.0,3.0,14.0,16.0,16.0
392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,5.0,3.0,3.0,3.0,3.0,3.0,10.0,8.0,7.0
393,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,4.0,1.0,3.0,4.0,5.0,0.0,11.0,12.0,10.0
394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2.0,3.0,3.0,3.0,5.0,5.0,8.0,9.0,9.0

In [ ]:
pd.concat([df1,df2],axis=0)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [ ]:
df4=pd.concat([df1,df2],ignore_index=False)
df4

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [ ]:
df5=df1.merge(df2,how='inner')
df5

Empty DataFrame
Columns: [school, sex, age, address, famsize, Pstatus, Medu, Fedu, Mjob, Fjob, reason, guardian, traveltime, studytime, failures, schoolsup, famsup, paid, activities, nursery, higher, internet, romantic, famrel, freetime, goout, Dalc, Walc, health, absences, G1, G2, G3]
Index: []

[0 rows x 33 columns]

In [ ]:
df6=df1.merge(df2,how='outer')
df6

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [ ]:
df7=df1.merge(df2,how='left')
df7

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,GP,M,17,U,GT3,T,1,2,at_home,services,...,4,4,4,4,5,5,12,7,8,8
193,GP,M,16,R,GT3,T,3,3,services,services,...,4,3,2,3,4,5,8,8,9,10
194,GP,M,16,U,GT3,T,2,3,other,other,...,5,3,3,1,1,3,0,13,14,14
195,GP,F,17,U,LE3,T,2,4,services,services,...,4,3,2,1,1,5,0,14,15,15
196,GP,M,17,U,GT3,T,4,4,services,teacher,...,5,2,3,1,2,5,4,17,15,16

In [ ]:
dataset['total_time_spent']=dataset['studytime']+dataset['traveltime']
dataset

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,total_time_spent
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,6,5,6,6,4
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,4,5,5,6,3
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,10,7,8,10,3
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,2,15,14,15,4
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,4,6,10,10,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,4,4,5,4,11,9,9,9,3
391,MS,M,17,U,LE3,T,3,1,services,services,...,4,5,3,4,2,3,14,16,16,3
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,3,3,3,3,3,10,8,7,2
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,1,3,4,5,0,11,12,10,4
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,2,3,3,3,5,5,8,9,9,2

In [ ]:
dataset['sex'].value_counts()

sex
F    208
M    185
Name: count, dtype: int64

In [ ]:
dataset.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,total_time_spent
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190,3.483544
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443,1.035711
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000,2.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000,3.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000,3.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000,4.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000,8.000000

In [ ]:
data = np.arange(15).reshape((3,5))
indexers = ['Rainfall', 'Humidity', 'Wind']
dframe1 = pd.DataFrame(data, index=indexers, columns=['Bergen', 'Oslo', 'Trondheim', 'Stavanger', 'Kristiansand'])
dframe1

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

In [ ]:
stacked = df3.stack()
stacked

0    school       GP
     sex           F
     age          18
     address       U
     famsize     GT3
                ...
394  health        5
     absences      5
     G1            8
     G2            9
     G3            9
Length: 13029, dtype: object

In [ ]:
stacked.unstack()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [ ]:
df1.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
192    False
193    False
194    False
195    False
196    False
Length: 197, dtype: bool

In [ ]:
df1.drop_duplicates()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,GP,M,17,U,GT3,T,1,2,at_home,services,...,4,4,4,4,5,5,12,7,8,8
193,GP,M,16,R,GT3,T,3,3,services,services,...,4,3,2,3,4,5,8,8,9,10
194,GP,M,16,U,GT3,T,2,3,other,other,...,5,3,3,1,1,3,0,13,14,14
195,GP,F,17,U,LE3,T,2,4,services,services,...,4,3,2,1,1,5,0,14,15,15
196,GP,M,17,U,GT3,T,4,4,services,teacher,...,5,2,3,1,2,5,4,17,15,16

In [ ]:
df1['sex']= 'F'
df1
df1.drop_duplicates(['sex'])

<ipython-input-20-a8200ae6cb3b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['sex']= 'F'

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6

In [ ]:
dframe1.replace(to_replace=13,value=np.nan)

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2        3.0             4
Humidity       5     6          7        8.0             9
Wind          10    11         12        NaN            14

In [ ]:
dframe1.replace(to_replace=[13,14],value=np.nan)

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2        3.0           4.0
Humidity       5     6          7        8.0           9.0
Wind          10    11         12        NaN           NaN

In [ ]:
dframe1['Bergen'] =np.nan
dframe1.loc['Air Pollution'] = np.arange(10,15)
dframe1.loc['Rainfall'] = np.nan
dframe1['Oslo'] = np.nan
dframe1['Bergen']['Rainfall'] = 30
dframe1

               Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall         30.0   NaN        NaN        NaN           NaN
Humidity          NaN   NaN        7.0        8.0           9.0
Wind              NaN   NaN       12.0       13.0          14.0
Air Pollution    10.0   NaN       12.0       13.0          14.0

In [ ]:
dframe1.isnull()

               Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall        False  True       True       True          True
Humidity         True  True      False      False         False
Wind             True  True      False      False         False
Air Pollution   False  True      False      False         False

In [ ]:
dframe1.notnull()

               Bergen   Oslo  Trondheim  Stavanger  Kristiansand
Rainfall         True  False      False      False         False
Humidity        False  False       True       True          True
Wind            False  False       True       True          True
Air Pollution    True  False       True       True          True

In [ ]:
dframe1.isnull().sum()

Bergen          2
Oslo            4
Trondheim       1
Stavanger       1
Kristiansand    1
dtype: int64

In [ ]:
dframe1.isnull().sum().sum()

9

In [ ]:
dframe1.count()

Bergen          2
Oslo            0
Trondheim       3
Stavanger       3
Kristiansand    3
dtype: int64

In [ ]:
dframe1.Bergen[dframe1.Bergen.notnull()]

Rainfall         30.0
Air Pollution    10.0
Name: Bergen, dtype: float64

In [ ]:
dframe1.dropna()

Empty DataFrame
Columns: [Bergen, Oslo, Trondheim, Stavanger, Kristiansand]
Index: []

In [ ]:
dframe1.dropna(how='all')

               Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall         30.0   NaN        NaN        NaN           NaN
Humidity          NaN   NaN        7.0        8.0           9.0
Wind              NaN   NaN       12.0       13.0          14.0
Air Pollution    10.0   NaN       12.0       13.0          14.0

In [ ]:
dframe1.dropna(how='all',axis=1)

               Bergen  Trondheim  Stavanger  Kristiansand
Rainfall         30.0        NaN        NaN           NaN
Humidity          NaN        7.0        8.0           9.0
Wind              NaN       12.0       13.0          14.0
Air Pollution    10.0       12.0       13.0          14.0

In [ ]:
dframe1.dropna(thresh=2,axis=1)

               Bergen  Trondheim  Stavanger  Kristiansand
Rainfall         30.0        NaN        NaN           NaN
Humidity          NaN        7.0        8.0           9.0
Wind              NaN       12.0       13.0          14.0
Air Pollution    10.0       12.0       13.0          14.0

In [ ]:
ar1=np.array([100,200,np.nan,300])
ser1=pd.Series(ar1)
ar1.mean(),ser1.mean()

(nan, 200.0)

In [ ]:
ser2 = dframe1.Bergen
ser2.sum()

40.0

In [ ]:
ser2.cumsum()

Rainfall         30.0
Humidity          NaN
Wind              NaN
Air Pollution    40.0
Name: Bergen, dtype: float64

In [ ]:
filldataframe=dframe1.fillna(0)
filldataframe

               Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall         30.0   0.0        0.0        0.0           0.0
Humidity          0.0   0.0        7.0        8.0           9.0
Wind              0.0   0.0       12.0       13.0          14.0
Air Pollution    10.0   0.0       12.0       13.0          14.0

In [ ]:
dframe1.mean()
filldataframe.mean()

Bergen          10.00
Oslo             0.00
Trondheim        7.75
Stavanger        8.50
Kristiansand     9.25
dtype: float64

In [ ]:
dframe1.fillna(method='ffill')

<ipython-input-39-ac1efdf2eccf>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dframe1.fillna(method='ffill')

               Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall         30.0   NaN        NaN        NaN           NaN
Humidity         30.0   NaN        7.0        8.0           9.0
Wind             30.0   NaN       12.0       13.0          14.0
Air Pollution    10.0   NaN       12.0       13.0          14.0

In [ ]:
dframe1.fillna(method='bfill')

<ipython-input-40-5e39827b3e85>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dframe1.fillna(method='bfill')

               Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall         30.0   NaN        7.0        8.0           9.0
Humidity         10.0   NaN        7.0        8.0           9.0
Wind             10.0   NaN       12.0       13.0          14.0
Air Pollution    10.0   NaN       12.0       13.0          14.0

In [ ]:
Marks=[12,23,34,45,56,67,78,89,90,10]
bins=[0,20,40,60,80,100]
grade=pd.cut(Marks,bins)
grade

[(0, 20], (20, 40], (20, 40], (40, 60], (40, 60], (60, 80], (60, 80], (80, 100], (80, 100], (0, 20]]
Categories (5, interval[int64, right]): [(0, 20] < (20, 40] < (40, 60] < (60, 80] < (80, 100]]

In [ ]:
pd.value_counts(grade)

<ipython-input-42-b0de5cbf5331>:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(grade)

(0, 20]      2
(20, 40]     2
(40, 60]     2
(60, 80]     2
(80, 100]    2
Name: count, dtype: int64

In [ ]:
bin_names=['F','D','C','B','A']
grade=pd.cut(Marks,bins,labels=bin_names)
grade

['F', 'D', 'D', 'C', 'C', 'B', 'B', 'A', 'A', 'F']
Categories (5, object): ['F' < 'D' < 'C' < 'B' < 'A']

In [ ]:
pd.cut(np.random.randn(50),6,precision=2)

[(-0.011, 0.66], (0.66, 1.33], (1.33, 2.0], (0.66, 1.33], (0.66, 1.33], ..., (-0.68, -0.011], (-0.68, -0.011], (0.66, 1.33], (0.66, 1.33], (-0.68, -0.011]]
Length: 50
Categories (6, interval[float64, right]): [(-2.03, -1.35] < (-1.35, -0.68] < (-0.68, -0.011] <
                                           (-0.011, 0.66] < (0.66, 1.33] < (1.33, 2.0]]

In [ ]:
random_integers=np.random.rand(400)
quartered=pd.qcut(random_integers,4)
quartered

[(0.00234, 0.254], (0.486, 0.742], (0.486, 0.742], (0.742, 0.999], (0.742, 0.999], ..., (0.00234, 0.254], (0.486, 0.742], (0.254, 0.486], (0.486, 0.742], (0.254, 0.486]]
Length: 400
Categories (4, interval[float64, right]): [(0.00234, 0.254] < (0.254, 0.486] < (0.486, 0.742] <
                                           (0.742, 0.999]]

In [ ]:
pd.value_counts(quartered)

<ipython-input-50-278e496f70ef>:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartered)

(0.00234, 0.254]    100
(0.254, 0.486]      100
(0.486, 0.742]      100
(0.742, 0.999]      100
Name: count, dtype: int64

In [ ]:
Timespent= dataset['total_time_spent']
Timespent[np.abs(Timespent)>5]

11     6
69     6
70     6
76     6
95     6
108    8
134    6
140    6
164    6
204    6
228    6
282    6
293    6
334    6
375    7
Name: total_time_spent, dtype: int64

In [ ]:
dataset[np.abs(Timespent)>5]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,total_time_spent
11,GP,F,15,U,GT3,T,2,1,services,other,...,2,2,1,1,4,4,10,12,12,6
69,GP,F,15,R,LE3,T,3,1,other,other,...,4,2,2,3,3,12,16,16,16,6
70,GP,M,16,U,GT3,T,3,1,other,other,...,3,2,1,1,5,0,13,15,15,6
76,GP,M,15,U,GT3,?,4,0,teacher,other,...,4,3,1,1,1,8,11,11,10,6
95,GP,F,15,R,GT3,T,1,1,at_home,other,...,1,2,1,1,1,2,7,10,10,6
108,GP,M,15,R,GT3,T,4,4,other,other,...,3,5,3,5,1,6,10,13,13,8
134,GP,M,15,R,GT3,T,3,4,at_home,teacher,...,3,3,1,1,5,0,9,0,0,6
140,GP,M,15,U,GT3,T,4,3,teacher,services,...,2,2,1,1,3,0,7,9,0,6
164,GP,M,17,R,LE3,T,1,1,other,services,...,3,5,1,5,5,0,5,8,7,6
204,GP,F,16,R,GT3,T,2,2,services,services,...,3,5,1,1,5,6,10,10,11,6
228,GP,M,18,U,LE3,T,2,1,at_home,other,...,3,2,4,5,3,14,10,8,9,6
282,GP,F,18,R,LE3,T,1,1,at_home,other,...,2,2,1,1,3,1,12,12,12,6
293,GP,F,17,R,LE3,T,3,1,services,other,...,1,2,1,1,3,6,18,18,18,6
334,GP,F,18,R,GT3,T,2,2,at_home,other,...,4,4,1,1,4,0,10,9,0,6
375,MS,F,18,R,GT3,T,1,1,other,other,...,3,2,1,2,4,2,8,8,10,7